src/objects/FieloPLT__Program__c.object
<CustomObject>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Distributor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distributor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvoiceNumber__c</fullName>
        <label>Invoice Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{00000000}</displayFormat>
        <label>Invoice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/InvoiceItem__c.object
<CustomObject>
    <description>An Invoice Item is an incentivized product or service charged on an Invoice.</description>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Invoice on which an Invoice Item appears.</description>
        <inlineHelpText>This is the Invoice that this Invoice Item is on.</inlineHelpText>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Items</relationshipLabel>
        <relationshipName>InvoiceItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>The quantity of an Invoice Item purchased.</description>
        <inlineHelpText>Enter the quantity purchased of the item.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <description>The price per unit of an Invoice Item.</description>
        <inlineHelpText>Enter the price per unit of the item purchased.</inlineHelpText>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Invoice Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PhotoUploadControllerTest.cls
@isTest
private class PhotoUploadControllerTest {

@isTest public static void test(){
    List<FieloPLT__Program__c> programs;
    List<FieloPLT__Member__c> members;
    List<FieloPRP__Invoice__c> invoices;
    programs = MockUpFactory.createPrograms('Default', 1);
    programs[0].FieloPRP__RequestInvoiceProducts__c = true;
    insert programs;

    members = MockUpFactory.createMembers(programs[0].Id,2);
    insert members;

    Account distributor = new Account(name = 'Fielo');
    
    insert distributor;

    invoices = MockUpFactory.createInvoices(members[0].Id,1);
    invoices[0].Distributor__c = distributor.Id;
    invoices[0].InvoiceNumber__c = '123456';
    

    insert invoices;

    InvoiceItem__c item = new InvoiceItem__c(
        Quantity__c = 10.0,
        UnitPrice__c = 50.0,
        Invoice__c = invoices[0].Id
    );

    insert item;

    List<Folder> folders = [SELECT DeveloperName,Id,NamespacePrefix FROM Folder WHERE DeveloperName='FieloImages' AND NamespacePrefix='FieloPLT'];
    Document doc = new Document();
    doc.Name='Logo Fielo';
    doc.Body=EncodingUtil.Base64Decode('/services/data/v42/sobjects/Document/01546000000SgEKAA0/Body');
    doc.ContentType = 'image/png';
    doc.folderId=folders[0].Id;
    insert doc;



    PhotoUploadController controller = new PhotoUploadController();
    controller.folderUniqueName = 'FieloPLT__FieloImages';
    Id folderId = controller.folderId;
    List<PicklistController.Entry> documents = controller.existingDocuments;
    controller.recordObject = doc;
    controller.fieldNameObject = 'Id';
    controller.externalURLNameObject = 'Id';
    String enc = controller.getEncImage();
    Boolean image = controller.hasImage;
    RemoteActionResult result1 = PhotoUploadController.save(doc,folderId,'Document','Id','Id','existing',enc);
    RemoteActionResult result = PhotoUploadController.save(doc,folderId,'Document','Id','Id','cropped',enc);
    RemoteActionResult result2 = PhotoUploadController.remove(doc,'Id','Id');
    //Force the DML Exception
    RemoteActionResult result3 = PhotoUploadController.remove(doc,'Description','IsPublic');
    }


}