src/objects/FieloPLT__Program__c.object
<CustomObject>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Distributor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distributor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvoiceNumber__c</fullName>
        <label>Invoice Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UniqueKey__c</fullName>
        <label>Unique Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{00000000}</displayFormat>
        <label>Invoice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InvoiceDuplicateDefault.cls
public class InvoiceDuplicateDefault implements InvoiceDuplicateInterface{
	
	public void setUniqueKey(List<Invoice__c> invoices, Boolean isUpdate){
		Set<Id> memberIds = new Set<Id>();
		for(Invoice__c invoice : invoices){
			if(invoice.Distributor__c != null && invoice.InvoiceNumber__c != null){
				if(!isUpdate || (invoice.Distributor__c != ((Invoice__c)Trigger.oldMap.get(invoice.Id)).Distributor__c || invoice.InvoiceNumber__c != ((Invoice__c)Trigger.oldMap.get(invoice.Id)).InvoiceNumber__c)){
					memberIds.add(invoice.Member__c);
				}
			}
		}

		Map<Id,FieloPLT__Member__c> membersMap = new Map<Id,FieloPLT__Member__c>([SELECT FieloPLT__Program__c FROM FieloPLT__Member__c WHERE Id in : memberIds]);
		for(Invoice__c invoice : invoices){
			if(invoice.Distributor__c != null && invoice.InvoiceNumber__c != null){
				if(!isUpdate || (invoice.Distributor__c != ((Invoice__c)Trigger.oldMap.get(invoice.Id)).Distributor__c || invoice.InvoiceNumber__c != ((Invoice__c)Trigger.oldMap.get(invoice.Id)).InvoiceNumber__c)){
					invoice.UniqueKey__c = String.valueOf(membersMap.get(invoice.Member__c).FieloPLT__Program__c) + String.valueOf(invoice.Distributor__c) + invoice.InvoiceNumber__c;
				}
			}else{
				invoice.UniqueKey__c = null;
			}
		}
	}

	public void validateDuplicates(List<Invoice__c> invoices, Boolean isUpdate){
		Set<String> uniqueKeys = new Set<String>();
		for(Invoice__c invoice : invoices){
			if(String.isNotBlank(invoice.UniqueKey__c)){
				if(!isUpdate || (invoice.Distributor__c != ((Invoice__c)Trigger.oldMap.get(invoice.Id)).Distributor__c || invoice.InvoiceNumber__c != ((Invoice__c)Trigger.oldMap.get(invoice.Id)).InvoiceNumber__c)){
					uniqueKeys.add(invoice.UniqueKey__c);
				}
			}
		}

		if(!uniqueKeys.isEmpty()){
			Set<String> existingKeys = new Set<String>();
			for(Invoice__c invoice : [SELECT UniqueKey__c FROM Invoice__c WHERE Status__c = 'Approved' AND UniqueKey__c in : uniqueKeys]){
				existingKeys.add(invoice.UniqueKey__c);
			}

			for(Invoice__c invoice : invoices){
				if(String.isNotBlank(invoice.UniqueKey__c) && existingKeys.contains(invoice.UniqueKey__c)){
					invoice.addError(Label.DuplicatedInvoiceRecord);
				}else if(invoice.Status__c == 'Approved'){
					existingKeys.add(invoice.UniqueKey__c);
				}
			}
		}
	}

}