src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>RejectReason__c</fullName>
        <label>Reject Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Invalid Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid Image</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Image Attached</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Products</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{00000000}</displayFormat>
        <label>Invoice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ApprovalHistoryController.cls
public with sharing class ApprovalHistoryController {
	public Boolean noRecords {get;set;}
	public Invoice__c cRecord {get;set;}

	public class RelatedColumn  {
		public String id{get;set;}
		public String Type{get;set;}
		public String Name{get;set;}
		public String Label{get;set;}
		public Boolean getIsCrossFormula(){return (Name.countMatches('.') == 0 || (Name.countMatches('.') ==  1 && Name.endsWith('.Name'))) ? false : true;}

		public RelatedColumn(String id, String type, String name, String label) {
			this.id = id;
			this.type = type;
			this.name = name;
			this.label = label;
		}
	}

	public class Row{
		public String action {get;set;}
		public Datetime stepDate {get;set;}
		public string status {get;set;}
		public string comments {get;set;}

		public Row(String action, Datetime stepDate, String status, String comments) {
			this.action = action;
			this.stepDate = stepDate;
			this.status = status;
			this.comments = comments;
		}
	}

	public List<RelatedColumn> columns { get {
		if (columns == null) {
			columns = new List<RelatedColumn>();
			columns.add(new RelatedColumn('1', 'string', 'action', 'Action'));
			columns.add(new RelatedColumn('2', 'datetime', 'stepDate', 'Date'));
			columns.add(new RelatedColumn('3', 'string', 'status', 'Status'));
			columns.add(new RelatedColumn('6', 'string', 'comments', 'Comments'));
		}
		return columns;
	} set; }

	public List<Row> recordObjects {get {
		if (recordObjects == null) {
			recordObjects = new List<Row>();
			
			if (cRecord.Id!=null) {
				List<ProcessInstance> pis = InvoicesSelector.selectAllInvoiceApprovalProcessInstance(new Set<Id>{cRecord.Id});

				if (!pis.isEmpty()) {
					for (ProcessInstance pi: pis) {
						if (pi.StepsAndWorkitems != null) {
							for (ProcessInstanceHistory pih : pi.StepsAndWorkitems) {
								recordObjects.add(new Row((pih.StepStatus == 'Started' ? 'Approval Request Submitted' : ('Step: ' + (pih.ProcessNode!=null?pih.ProcessNode.Name:''))),pih.CreatedDate,pih.StepStatus == 'Started' ? 'Submitted' : pih.StepStatus,pih.Comments));
							}
						}
					}
				} else {
					List<Invoice__c> existingInvoices = new InvoicesSelector(new Set<String>{'FieloPRP__Status__c','FieloPRP__RejectReason__c','FieloPRP__Comments__c','LastModifiedDate'}).selectById(new Set<Id>{cRecord.Id});

					if (!existingInvoices.isEmpty()) {
						if (existingInvoices[0].Status__c == 'Approved' || existingInvoices[0].Status__c == 'Rejected') {
							recordObjects.add(new Row('Approval Request Submitted',existingInvoices[0].LastModifiedDate,existingInvoices[0].Status__c,(existingInvoices[0].Status__c == 'Approved' ? '' : existingInvoices[0].RejectReason__c + ': ') + (existingInvoices[0].Comments__c!=null?existingInvoices[0].Comments__c:'')));
						}
					}
				}
			}
		}
		return recordObjects;
	} set;}
}